### ISSUE TITLE
Feature request: option for English menu

### ISSUE THREAD

**Issue by anthrolisp** [WortgeschichteDigital/ZettelsTraum#1]
Is it possible to have an options for an English menu? Thank you in advance!

**Comment by WortgeschichteDigital** [comment]
Thanks for your request! I'd love to do that! But…

First of all, it would be a lot of work. Currently I'm not able to invest the time needed, especially as the app is not feature complete yet, which will be my primary field of work within the next month.

Second of all, I'd need a native speaker with a strong commitment to participate in the translation. There're a lot of technical terms about which I'm not sure how to translate them. So it would be kind of helpful if the collaborator were an English lexicographer or at least had some knowledge in that field.

Facing these obstacles, don't expect a fast solution. But I'll keep your request in mind. Honestly!

**Comment by WortgeschichteDigital** [comment]
I just implemented translations (English, Italian, French) for the window menus. This way you can get a general idea about the scope of the app.

Unfortunately, that's all there is and I won't tackle the issue to translate the whole app. That would require a lot of work, and our project is lacking the resources to do so. Besides, the app is specifically designed for lexicographers of the German language and in particular for our project [Wortgeschichte digital](https://www.zdl.org/wb/wortgeschichten/) (Digital Word History). That's why I kept the UI in German.

Nevertheless, I hope it'll help.

![ui](https://github.com/WortgeschichteDigital/ZettelsTraum/assets/55915607/14f6db9b-abb0-4536-86f9-6da71506123e)
